[package]
name = "geo_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.15"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
