[package]
name = "geo_traits"
version = "0.6.1"
edition = "2021"
authors = ["Fraser Balch <fraser.balch@gmail.com>"]
keywords = ["clifford", "geometric", "algebra"]
license = "MIT"

[dependencies]
num-traits = "0.2"
